FROM ubuntu:25.10

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends clang-21           \
                                               clang-tools-21     \
                                               cmake              \
                                               ninja-build        \
                                               ocl-icd-libopencl1 \
                                               ocl-icd-opencl-dev

RUN rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/clang++-21 /usr/bin/clang++ && \
    ln -s /usr/bin/clang-21   /usr/bin/clang

WORKDIR /src
COPY . .

RUN rm -rf build/
RUN cmake -B build -DCMAKE_CXX_COMPILER=clang++ \
                   -DCMAKE_BUILD_TYPE=Release \
                   -G Ninja

RUN cmake --build build

    


